spring.application.name=simple_auth
spring.data.mongodb.uri=${DB_ACCESS_KEY}
spring.data.mongodb.database==${DB_NAME}
spring.app.jwtExpirationMs=${JWT_EXPIRY_INTERVAL}
cors.allowed-origins=${CORS_ALLOWED_DOMAINS}
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.private-path=/keys/private.pem
jwt.public-path=/keys/public.pem

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true